apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create_repo
  tile: Create Repo
  description: Template to create Repo 
spec:
  owner: raj
  type: service
  parameters:
    - title: Inputs
      required:
        - name
      properties:
        name:
          title: namespace
          type: string
          description: type the new namespace
  steps:
    - id: fetch-base
      name: fetch-base
      action: fetch:template
      input:
        url: ./template
        values: 
          name: ${{ parameters.name }}